### ISSUE TITLE
Problem with installing pty.js

### ISSUE THREAD

**Issue by zaozaool** [chjj/pty.js#125]
Does anyone knows what's going on about this? 
```
> pty.js@0.2.7-1 install /home/vagrant/.c9/node_modules/pty.js
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: node-v0.12.0.tar.gz local checksum e341c6b919d2b391f5ba5bfa6a00a0e112c7227f297591074ab4d8b553b6f5e1 not match remote 9700e23af4e9b3643af48cef5f2ad20a1331ff531a12154eef2bfb0bb1682e32
gyp ERR! stack     at deref (/home/vagrant/.c9/node/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:299:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/home/vagrant/.c9/node/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:340:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:908:16
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Linux 3.2.0-23-generic-pae
gyp ERR! command "node" "/home/vagrant/.c9/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/.c9/node_modules/pty.js
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "/home/vagrant/.c9/node/bin/node" "/home/vagrant/.c9/node/bin/npm" "install" "pty.js@0.2.7-1"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.7-1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.7-1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/.c9/npm-debug.log
```
Thanks.

**Comment by zaozaool** [comment]
OK, nobody knew it, more information please check [Problem with installing pty.js!](https://github.com/c9/core/issues/109), it may be can help you.
