### ISSUE TITLE
node-gyp fails with Apple Command Line Tools 10.10

### ISSUE THREAD

**Issue by malandrew** [chjj/pty.js#139]
Looks like Apple Command Line Tools 10.10 introduced some change that causes node-gyp to fail when installing pty.js

```
$ cd $TMPDIR
$ npm install pty.js --verbose
npm info it worked if it ends with ok
npm verb cli [ 'node', '/usr/local/bin/npm', 'install', 'pty.js', '--verbose' ]
npm info using npm@2.12.1
npm info using node@v0.10.36
npm verb node symlink /usr/local/bin/node
npm verb install initial load of /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/package.json
npm verb readDependencies loading dependencies from /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/package.json
npm verb cache add spec pty.js
npm verb addNamed "*" is a valid semver range for pty.js
npm verb addNameRange registry:https://registry.npmjs.org/pty.js not in flight; fetching
npm verb request uri https://registry.npmjs.org/pty.js
npm verb request always-auth set; sending authorization
npm info attempt registry request try #1 at 13:02:04
npm verb request id 36f068ec39bebbdb
npm verb etag "52Z6QPSCM48U1FO4G39E8X9GU"
npm http request GET https://registry.npmjs.org/pty.js
npm http 304 https://registry.npmjs.org/pty.js
npm verb etag https://registry.npmjs.org/pty.js from cache
npm verb get saving pty.js to /Users/someuser/.npm/registry.npmjs.org/pty.js/.cache.json
npm verb addNamed "0.3.0" is a plain semver version for pty.js
npm verb afterAdd /Users/someuser/.npm/pty.js/0.3.0/package/package.json not in flight; writing
npm verb afterAdd /Users/someuser/.npm/pty.js/0.3.0/package/package.json written
npm info install pty.js@0.3.0 into /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T
npm info installOne pty.js@0.3.0
npm verb installOne of pty.js to /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T not in flight; installing
npm verb lock using /Users/someuser/.npm/_locks/pty-js-490b4442a4344c84.lock for /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js
npm verb unbuild node_modules/pty.js
npm verb gentlyRm don't care about contents; nuking /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js
npm verb tar unpack /Users/someuser/.npm/pty.js/0.3.0/package.tgz
npm verb tar unpacking to /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js
npm verb gentlyRm don't care about contents; nuking /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js
npm verb write writing to /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/package.json
npm info preinstall pty.js@0.3.0
npm verb readDependencies loading dependencies from /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/package.json
npm verb readDependencies loading dependencies from /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/package.json
npm verb cache add spec extend@~1.2.1
npm verb cache add spec nan@2.0.5
npm verb addNamed ">=1.2.1 <1.3.0" is a valid semver range for extend
npm verb addNameRange registry:https://registry.npmjs.org/extend not in flight; fetching
npm verb addNamed "2.0.5" is a plain semver version for nan
npm verb addNameVersion registry:https://registry.npmjs.org/nan not in flight; fetching
npm verb request uri https://registry.npmjs.org/extend
npm verb request always-auth set; sending authorization
npm info attempt registry request try #1 at 13:02:05
npm verb etag "45R1SNLPKCV2JIDZCHTS8F2R4"
npm http request GET https://registry.npmjs.org/extend
npm verb request uri https://registry.npmjs.org/nan
npm verb request always-auth set; sending authorization
npm info attempt registry request try #1 at 13:02:05
npm verb etag "1L4RU1AM541YSVP1YQFXG1Y1J"
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm verb etag https://registry.npmjs.org/nan from cache
npm verb get saving nan to /Users/someuser/.npm/registry.npmjs.org/nan/.cache.json
npm http 304 https://registry.npmjs.org/extend
npm verb etag https://registry.npmjs.org/extend from cache
npm verb get saving extend to /Users/someuser/.npm/registry.npmjs.org/extend/.cache.json
npm verb addNamed "1.2.1" is a plain semver version for extend
npm verb afterAdd /Users/someuser/.npm/nan/2.0.5/package/package.json not in flight; writing
npm verb afterAdd /Users/someuser/.npm/extend/1.2.1/package/package.json not in flight; writing
npm verb afterAdd /Users/someuser/.npm/nan/2.0.5/package/package.json written
npm verb afterAdd /Users/someuser/.npm/extend/1.2.1/package/package.json written
npm info install nan@2.0.5 into /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js
npm info install extend@1.2.1 into /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js
npm info installOne nan@2.0.5
npm verb installOne of nan to /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js not in flight; installing
npm info installOne extend@1.2.1
npm verb installOne of extend to /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js not in flight; installing
npm verb lock using /Users/someuser/.npm/_locks/nan-c95e79af59aa7a79.lock for /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/nan
npm verb lock using /Users/someuser/.npm/_locks/extend-4dae6cca5486d869.lock for /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/extend
npm verb unbuild node_modules/pty.js/node_modules/nan
npm verb unbuild node_modules/pty.js/node_modules/extend
npm verb gentlyRm don't care about contents; nuking /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/nan
npm verb gentlyRm don't care about contents; nuking /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/extend
npm verb tar unpack /Users/someuser/.npm/nan/2.0.5/package.tgz
npm verb tar unpacking to /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/nan
npm verb gentlyRm don't care about contents; nuking /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/nan
npm verb tar unpack /Users/someuser/.npm/extend/1.2.1/package.tgz
npm verb tar unpacking to /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/extend
npm verb gentlyRm don't care about contents; nuking /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/extend
npm verb write writing to /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/extend/package.json
npm info preinstall extend@1.2.1
npm verb readDependencies loading dependencies from /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/extend/package.json
npm verb readDependencies loading dependencies from /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/extend/package.json
npm verb about to build /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/extend
npm info build /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/extend
npm info linkStuff extend@1.2.1
npm verb linkBins extend@1.2.1
npm verb linkMans extend@1.2.1
npm verb rebuildBundles extend@1.2.1
npm info install extend@1.2.1
npm info postinstall extend@1.2.1
npm verb unlock done using /Users/someuser/.npm/_locks/extend-4dae6cca5486d869.lock for /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/extend
npm verb write writing to /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/nan/package.json
npm info preinstall nan@2.0.5
npm verb readDependencies loading dependencies from /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/nan/package.json
npm verb readDependencies loading dependencies from /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/nan/package.json
npm verb about to build /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/nan
npm info build /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/nan
npm info linkStuff nan@2.0.5
npm verb linkBins nan@2.0.5
npm verb linkMans nan@2.0.5
npm verb rebuildBundles nan@2.0.5
npm info install nan@2.0.5
npm info postinstall nan@2.0.5
npm verb unlock done using /Users/someuser/.npm/_locks/nan-c95e79af59aa7a79.lock for /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/node_modules/nan
npm verb about to build /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js
npm info build /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js
npm info linkStuff pty.js@0.3.0
npm verb linkBins pty.js@0.3.0
npm verb linkMans pty.js@0.3.0
npm verb rebuildBundles pty.js@0.3.0
npm verb rebuildBundles [ 'extend', 'nan' ]
npm info install pty.js@0.3.0

> pty.js@0.3.0 install /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ 'node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@2.0.1
gyp info using node@0.10.36 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `python2 -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: v0.10.36
gyp verb command install [ 'v0.10.36' ]
gyp verb install input version string "v0.10.36"
gyp verb install installing version: 0.10.36
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 0.10.36
gyp verb build dir attempting to create "build" dir: /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/build
gyp verb build dir "build" dir needed to be created? /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/build/config.gypi
gyp verb config.gypi checking for gypi file: /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/config.gypi
gyp verb common.gypi checking for gypi file: /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/someuser/.node-gyp/0.10.36/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/someuser/.node-gyp/0.10.36',
gyp info spawn args   '-Dmodule_root_dir=/private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/someuser/.node-gyp/0.10.36
gyp verb `which` succeeded for `make` /usr/local/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/build'
  g++ '-DNODE_GYP_MODULE_NAME=pty' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/someuser/.node-gyp/0.10.36/src -I/Users/someuser/.node-gyp/0.10.36/deps/uv/include -I/Users/someuser/.node-gyp/0.10.36/deps/v8/include -I../node_modules/nan  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/pty/src/unix/pty.o.d.raw  -c -o Release/obj.target/pty/src/unix/pty.o ../src/unix/pty.cc
  g++ -bundle -undefined dynamic_lookup -Wl,-search_paths_first -mmacosx-version-min=10.5 -arch x86_64 -L./Release  -o Release/pty.node Release/obj.target/pty/src/unix/pty.o -L/usr/lib -L/usr/local/lib
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
pty.target.mk:149: recipe for target 'Release/pty.node' failed
make: *** [Release/pty.node] Error 1
make: Leaving directory '/private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm verb unsafe-perm in lifecycle true
npm info pty.js@0.3.0 Failed to exec install script
npm verb unlock done using /Users/someuser/.npm/_locks/pty-js-490b4442a4344c84.lock for /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js
npm verb stack Error: pty.js@0.3.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
npm verb stack     at EventEmitter.emit (events.js:98:17)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at ChildProcess.emit (events.js:98:17)
npm verb stack     at maybeClose (child_process.js:766:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm verb pkgid pty.js@0.3.0
npm verb cwd /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "pty.js" "--verbose"
npm ERR! node v0.10.36
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/pty.js
npm info preuninstall pty.js@0.3.0
npm info uninstall pty.js@0.3.0
npm verb unbuild rmStuff pty.js@0.3.0 from /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules
npm info postuninstall pty.js@0.3.0
npm verb gentlyRm don't care about contents; nuking /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/node_modules/pty.js

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/ld/nstwtv2x1n1fy1p6yhshtp6h0000gn/T/npm-debug.log
$
```

**Comment by malandrew** [comment]
Found this: https://github.com/Homebrew/homebrew/issues/40653

Apparently, you need to have XCode 7 installed and set as the default toolchain, but I couldn't get that to work. The workaround presented in that issue did work. I don't understand why the new version of command line tools would be broken, but not Xcode7.
