### ISSUE TITLE
node-gyp rebuild error: expected unqualified-id before 'using'

### ISSUE THREAD

**Issue by mark-hahn** [chjj/pty.js#140]
I'm trying to install the Atom term2 but I can't get pty.js to build.  I've installed many node-gyp npm modules so I'm pretty sure my build-chain is good.

Ubuntu 14.04
Crouton on Chromebook Pixel 2015
Node v0.12.4

```
$ apm install term2
Installing term2 to /root/.atom/packages ✗

> pty.js@0.2.13 install /tmp/apm-install-dir-11594-27961-12bh7xz/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

make: Entering directory `/tmp/apm-install-dir-11594-27961-12bh7xz/node_modules/term2/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: Leaving directory `/tmp/apm-install-dir-11594-27961-12bh7xz/node_modules/term2/node_modules/pty.js/build'

In file included from /root/.atom/.node-gyp/.node-gyp/0.30.7/src/node.h:42:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/unix/pty.cc:20:
/root/.atom/.node-gyp/.node-gyp/0.30.7/deps/v8/include/v8.h:543:1: error: expected unqualified-id before 'using'
/root/.atom/.node-gyp/.node-gyp/0.30.7/deps/v8/include/v8.h:922:1: error: expected unqualified-id before 'using'
../src/unix/pty.cc: In function 'void PtyFork(const v8::FunctionCallbackInfo<v8::Value>&)':
../src/unix/pty.cc:227:34: warning: ignoring return value of 'int chdir(const char*)', declared with attribute warn_unused_result [-Wunused-result]
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.14.0
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11594-27961-12bh7xz/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.14.0
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/root/.atom/.apm/.apmrc" "--userconfig" "/root/.atom/.apmrc" "install" "/tmp/d-11594-27961-1ezk8px/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11594-27961-12bh7xz/npm-debug.log


$ cat /tmp/apm-install-dir-11594-27961-12bh7xz/npm-debug.log
cat: /tmp/apm-install-dir-11594-27961-12bh7xz/npm-debug.log: No such file or directory
```

**Comment by helloncanella** [comment]
same here

**Comment by CristyTarantino** [comment]
+1

**Comment by dmishh** [comment]
+1

**Comment by uronly14me** [comment]
+1

**Comment by Will-Wright** [comment]
+1

**Comment by verajosemanuel** [comment]
Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

Same here
