### ISSUE TITLE
Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by MarshalW** [chjj/pty.js#144]
Now using node v5.4.1 (npm v3.3.12) when run npm install:

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

**Comment by AnuragKutumbale** [comment]
need a fix for this

**Comment by jmls** [comment]
yup. me too

**Comment by pasqLisena** [comment]
+1

**Comment by arkrozycki** [comment]
+1

**Comment by jaredallard** [comment]
Try installing `build-essential` on Debian/Ubuntu. Other things that might have helped me is updating npm, and node-gyp-install (fixed iojs back in the day)

**Comment by arkrozycki** [comment]
build-essential did nothing, centos 6.7, node 5.3.0

npm install

> pty.js@0.3.0 install /home/test/project/node_modules/pty.js
> node-gyp rebuild

make: Entering directory `/home/test/project/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from /home/test/.node-gyp/5.3.0/include/node/node.h:42,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/unix/pty.cc:20:
/home/test/.node-gyp/5.3.0/include/node/v8.h:336: error: expected unqualified-id before ‘using’
/home/test/.node-gyp/5.3.0/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/home/test/.node-gyp/5.3.0/include/node/v8.h:353: error: ‘nullptr’ was not declared in this scope
/home/test/.node-gyp/5.3.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/home/test/.node-gyp/5.3.0/include/node/v8.h:360: error: ‘nullptr’ was not declared in this scope
/home/test/.node-gyp/5.3.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/home/test/.node-gyp/5.3.0/include/node/v8.h:364: error: ‘nullptr’ was not declared in this scope
/home/test/.node-gyp/5.3.0/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/home/test/.node-gyp/5.3.0/include/node/v8.h:430: error: ‘nullptr’ was not declared in this scope
/home/test/.node-gyp/5.3.0/include/node/v8.h: At global scope:
/home/test/.node-gyp/5.3.0/include/node/v8.h:469: error: expected unqualified-id before ‘using’
/home/test/.node-gyp/5.3.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/home/test/.node-gyp/5.3.0/include/node/v8.h:794: error: ‘nullptr’ was not declared in this scope
/home/test/.node-gyp/5.3.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/home/test/.node-gyp/5.3.0/include/node/v8.h:819: error: ‘nullptr’ was not declared in this scope
/home/test/.node-gyp/5.3.0/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/home/test/.node-gyp/5.3.0/include/node/v8.h:831: error: ‘nullptr’ was not declared in this scope
/home/test/.node-gyp/5.3.0/include/node/v8.h: At global scope:
/home/test/.node-gyp/5.3.0/include/node/v8.h:856: error: expected unqualified-id before ‘using’
/home/test/.node-gyp/5.3.0/include/node/v8.h:1093: error: ‘nullptr’ was not declared in this scope
/home/test/.node-gyp/5.3.0/include/node/v8.h:1099: error: ‘nullptr’ was not declared in this scope
/home/test/.node-gyp/5.3.0/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/home/test/.node-gyp/5.3.0/include/node/v8.h:3204: error: ‘nullptr’ was not declared in this scope
/home/test/.node-gyp/5.3.0/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/home/test/.node-gyp/5.3.0/include/node/v8.h:7154: error: ‘nullptr’ was not declared in this scope
In file included from ../node_modules/nan/nan.h:184,
                 from ../src/unix/pty.cc:20:
../node_modules/nan/nan_maybe_43_inl.h: At global scope:
../node_modules/nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:31: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:36: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:41: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:46: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:51: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:60: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:65: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:70: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:77: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:84: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:92: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:99: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:109: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:115: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:119: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:126: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:131: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:136: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:140: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:146: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:151: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:157: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:163: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:169: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:175: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:181: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:187: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:195: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:202: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:206: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:210: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:214: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:218: error: expected initializer before ‘<’ token
In file included from ../node_modules/nan/nan.h:189,
                 from ../src/unix/pty.cc:20:
../node_modules/nan/nan_converters.h:14: error: ISO C++ forbids declaration of ‘MaybeLocal’ with no type
../node_modules/nan/nan_converters.h:14: error: expected ‘;’ before ‘<’ token
../node_modules/nan/nan_converters.h:16: error: ISO C++ forbids declaration of ‘Maybe’ with no type
../node_modules/nan/nan_converters.h:16: error: expected ‘;’ before ‘<’ token
../node_modules/nan/nan_converters.h:26: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:27: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:28: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:29: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:30: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:31: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:32: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:42: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:43: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:44: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:45: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:46: error: ‘return_t’ does not name a type
In file included from ../node_modules/nan/nan_converters.h:59,
                 from ../node_modules/nan/nan.h:189,
                 from ../src/unix/pty.cc:20:
../node_modules/nan/nan_converters_43_inl.h:18: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Boolean>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:19: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Number>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:20: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::String>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:21: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Object>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:22: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Integer>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:23: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Uint32>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:24: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Int32>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:34: error: ‘return_t’ in class ‘Nan::imp::ToFactory<bool>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:35: error: ‘return_t’ in class ‘Nan::imp::ToFactory<double>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:36: error: ‘return_t’ in class ‘Nan::imp::ToFactory<long int>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:37: error: ‘return_t’ in class ‘Nan::imp::ToFactory<unsigned int>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:38: error: ‘return_t’ in class ‘Nan::imp::ToFactory<int>’ does not name a type
In file included from ../node_modules/nan/nan.h:190,
                 from ../src/unix/pty.cc:20:
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Integer]’:
../node_modules/nan/nan_new.h:21: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Int32]’:
../node_modules/nan/nan_new.h:28: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Uint32]’:
../node_modules/nan/nan_new.h:35: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../node_modules/nan/nan_new.h: At global scope:
../node_modules/nan/nan_new.h:43: error: ISO C++ forbids declaration of ‘MaybeLocal’ with no type
../node_modules/nan/nan_new.h:43: error: expected ‘;’ before ‘<’ token
../node_modules/nan/nan_new.h:75: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:141: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:147: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:148: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:160: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:161: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:162: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:163: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:165: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:166: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:182: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:183: error: ‘return_t’ does not name a type
In file included from ../node_modules/nan/nan_new.h:189,
                 from ../node_modules/nan/nan.h:190,
                 from ../src/unix/pty.cc:20:
../node_modules/nan/nan_implementation_12_inl.h:56: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Date>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:209: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::RegExp>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:228: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Script>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:234: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Script>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:266: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:274: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:280: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:287: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:293: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:298: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:359: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::UnboundScript>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:366: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::UnboundScript>’ does not name a type
In file included from ../node_modules/nan/nan.h:190,
                 from ../src/unix/pty.cc:20:
../node_modules/nan/nan_new.h:291: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:297: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:303: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:309: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:315: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:321: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:327: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::RegExp>’ does not name a type
In file included from ../src/unix/pty.cc:20:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::Error(const char*)’:
../node_modules/nan/nan.h:641: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowError(const char*)’:
../node_modules/nan/nan.h:641: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::RangeError(const char*)’:
../node_modules/nan/nan.h:642: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowRangeError(const char*)’:
../node_modules/nan/nan.h:642: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::ReferenceError(const char*)’:
../node_modules/nan/nan.h:643: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowReferenceError(const char*)’:
../node_modules/nan/nan.h:643: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::SyntaxError(const char*)’:
../node_modules/nan/nan.h:644: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowSyntaxError(const char*)’:
../node_modules/nan/nan.h:644: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::TypeError(const char*)’:
../node_modules/nan/nan.h:645: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowTypeError(const char*)’:
../node_modules/nan/nan.h:645: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:653: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:675: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:691: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:704: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:721: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:727: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:735: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:742: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:748: error: expected initializer before ‘<’ token
/home/test/.node-gyp/5.3.0/include/node/v8.h: In member function ‘void Nan::Callback::SetFunction(const v8::Local<v8::Function>&)’:
/home/test/.node-gyp/5.3.0/include/node/v8.h:3019: error: argument dependent lookup finds ‘class v8::Set’
../node_modules/nan/nan.h:1368: error:   in call to ‘Set’
../node_modules/nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
../node_modules/nan/nan.h:1490: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
../node_modules/nan/nan.h:1508: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In member function ‘virtual void Nan::AsyncWorker::HandleErrorCallback()’:
../node_modules/nan/nan.h:1542: error: no matching function for call to ‘New(const char*)’
../node_modules/nan/nan.h: In function ‘void Nan::SetMethod(const T&, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../node_modules/nan/nan.h:1832: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::SetPrototypeMethod(v8::Local<v8::FunctionTemplate>, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../node_modules/nan/nan.h:1845: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
In file included from ../src/unix/pty.cc:20:
../node_modules/nan/nan.h: In function ‘void Nan::Export(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../node_modules/nan/nan.h:2116: error: no matching function for call to ‘New(const char*&)’
/home/test/.node-gyp/5.3.0/include/node/v8.h:3019: error: argument dependent lookup finds ‘class v8::Set’
../node_modules/nan/nan.h:2117: error:   in call to ‘Set’
../node_modules/nan/nan.h: In constructor ‘Nan::Tap::Tap(v8::Local<v8::Value>)’:
../node_modules/nan/nan.h:2124: error: no matching function for call to ‘To(v8::Local<v8::Value>&)’
../node_modules/nan/nan.h: In member function ‘void Nan::Tap::ok(bool, const char*)’:
../node_modules/nan/nan.h:2137: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In member function ‘void Nan::Tap::pass(const char*)’:
../node_modules/nan/nan.h:2143: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyFork(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/unix/pty.cc:245: error: ‘Set’ is not a member of ‘Nan’
../src/unix/pty.cc:246: error: no matching function for call to ‘New(const char [3])’
../src/unix/pty.cc:248: error: ‘Set’ is not a member of ‘Nan’
../src/unix/pty.cc:249: error: no matching function for call to ‘New(const char [4])’
../src/unix/pty.cc:251: error: ‘Set’ is not a member of ‘Nan’
../src/unix/pty.cc:252: error: no matching function for call to ‘New(const char [4])’
../src/unix/pty.cc:253: error: no matching function for call to ‘New(char [40])’
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyOpen(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/unix/pty.cc:311: error: ‘Set’ is not a member of ‘Nan’
../src/unix/pty.cc:312: error: no matching function for call to ‘New(const char [7])’
../src/unix/pty.cc:314: error: ‘Set’ is not a member of ‘Nan’
../src/unix/pty.cc:315: error: no matching function for call to ‘New(const char [6])’
../src/unix/pty.cc:317: error: ‘Set’ is not a member of ‘Nan’
../src/unix/pty.cc:318: error: no matching function for call to ‘New(const char [4])’
../src/unix/pty.cc:319: error: no matching function for call to ‘New(char [40])’
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyGetProc(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/unix/pty.cc:380: error: no matching function for call to ‘New(char*&)’
../src/unix/pty.cc: In function ‘void init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/unix/pty.cc:682: error: ‘Set’ is not a member of ‘Nan’
../src/unix/pty.cc:683: error: no matching function for call to ‘New(const char [5])’
../src/unix/pty.cc:685: error: ‘Set’ is not a member of ‘Nan’
../src/unix/pty.cc:686: error: no matching function for call to ‘New(const char [5])’
../src/unix/pty.cc:688: error: ‘Set’ is not a member of ‘Nan’
../src/unix/pty.cc:689: error: no matching function for call to ‘New(const char [7])’
../src/unix/pty.cc:691: error: ‘Set’ is not a member of ‘Nan’
../src/unix/pty.cc:692: error: no matching function for call to ‘New(const char [8])’
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
make: Leaving directory `/home/test/project/node_modules/pty.js/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.5-x86_64-linode61
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/test/project/node_modules/pty.js
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPACKAGEJSON project@1.0.0 No repository field.
npm ERR! Linux 4.1.5-x86_64-linode61
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/test/project/npm-debug.log

**Comment by jaredallard** [comment]
Now that's an issue I don't know how to help you with :(

**Comment by hbargaz** [comment]
Someone Help plz I have The Same Problem !!

**Comment by peterjosvai** [comment]
+1

**Comment by nasawz** [comment]
+1

**Comment by arkrozycki** [comment]
This might be happening on older versions, on centos 6.7 I was able to resolve the problem by installing a newer version of gcc, and setting the env variables for CXX to point to the new version and npm install worked.

**Comment by WindWen** [comment]
+1

**Comment by DerekTBrown** [comment]
+1

**Comment by LaKing** [comment]
Latest nan is 3.2.2.

Newer node versions fail if nan is not updated. Simply write 3.2.2 into package.json before npm install as a workaround..

Its more problematic with packages that have pty.js as dependency, I didn't find a solution for that yet.
I guess @chjj needs to publish the npm with the updated nan version.

**Comment by ecanuto** [comment]
I have the same problem on Debian and some Ubuntu running Node.js 0.10.x. Here I managed to get it fixed by running "npm i node-gyp" before "npm i" on every project using Node.js 0.10.x and pty.js.

**Comment by askucher** [comment]
+1

**Comment by summercloud** [comment]
i have the same problem,
but when i try it again and again,and it worked,this problem gone.
i don't know why.
`npm install
|
> pty.js@0.3.1 install /Users/summer/Documents/nephelefli/node/node_modules/pty.js
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:907:11)
gyp ERR! stack     at TLSWrap.onread (net.js:558:26)
gyp ERR! System Darwin 16.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/summer/Documents/nephelefli/node/node_modules/pty.js
gyp ERR! node -v v4.7.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.7.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/summer/Documents/nephelefli/node/npm-debug.log
npm install
|
> pty.js@0.3.1 install /Users/summer/Documents/nephelefli/node/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
npm WARN prefer global babel@5.8.38 should be installed with -g
npm WARN prefer global coffee-script@1.9.3 should be installed with -g

> fsevents@1.0.17 install /Users/summer/Documents/nephelefli/node/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/summer/Documents/nephelefli/node/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
pty.js@0.3.1 node_modules/pty.js
├── extend@1.2.1
└── nan@2.3.5
`

**Comment by jefersonpassos** [comment]
+1

**Comment by Tyriar** [comment]
I forked this project recently to https://github.com/Tyriar/node-pty, you might want to try it out. Quite a bit of work has gone into improving it.

**Comment by timruis** [comment]
try installing Phyton as a variable. https://www.python.org/downloads/
