### ISSUE TITLE
installation issues - child_pty@3.0.1 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by abarik1981** [chjj/pty.js#156]
I am not able to install pty.js@latest on RHEL5/node@5.6.0/npm@3.6.0/gcc@4.1.2 with `child_pty@3.0.1 install: node-gyp rebuild` error

	make: Entering directory `/home/admin/workspace/Mydr/node_Mydr/node-webterm/node_modules/child_pty/build'
	  CXX(target) Release/obj.target/exechelper/src/exechelper.o
	cc1plus: error: unrecognized command line option "-std=gnu++0x"
	make: *** [Release/obj.target/exechelper/src/exechelper.o] Error 1
	make: Leaving directory `/home/admin/workspace/Mydr/node_Mydr/node-webterm/node_modules/child_pty/build'
	gyp ERR! build error
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/home/admin/.nvm/v5.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
	gyp ERR! stack     at emitTwo (events.js:100:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	gyp ERR! System Linux 2.6.18-164.el5
	gyp ERR! command "/home/admin/.nvm/v5.6.0/bin/node" "/home/admin/.nvm/v5.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

**Comment by abarik1981** [comment]
However, with node@0.10.33 and nvm@1.4.28, pty.js@0.5.1 gets installed and it works (but not latest pty)

**Comment by piranna** [comment]
Seems the gcc version on the RHEL5 machine is too old, starting from Node.js 4.x.x it is needed gcc 4.8 or newer due to usage of C++11 features.

**Comment by abarik1981** [comment]
awesome... thanks

**Comment by abarik1981** [comment]
this fixed it for me...
cd /tmp/
tar xzf gcc-4.8.2.tar.gz
cd gcc-4.8.2
./contrib/download_prerequisites
cd ..
mkdir objdir
cd objdir
$PWD/../gcc-4.8.2/configure \
 --prefix=/opt/gcc-4.8.2\
 --enable-shared \
 --disable-bootstrap \
 --disable-libstdcxx-pch \
 --enable-languages=c,c++ \
 --enable-libgomp \
 --enable-host-shared \
 --disable-multilib                               \
 --enable-lto \
 --enable-threads=posix \
 --enable-tls \
 --disable-multiarch \
 --with-libelf=/tmp/gcc  \
 --with-fpmath=sse 
make
sudo make install
env CC=/opt/gcc-4.8.2/bin/gcc CXX=/opt/gcc-4.8.2/bin/g++ npm install pty.js

**Comment by piranna** [comment]
> this fixed it for me...

Yes, you are using gcc 4.8 :-)
