### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by hktalent** [chjj/pty.js#190]
# node -v
v8.4.0
# cat /etc/issue
Oracle Linux Server release 6.3
Kernel \r on an \m

# proxychains4 npm install -g pty.js
```
[proxychains] config file found: /usr/local//etc/proxychains.conf
[proxychains] preloading /usr/local//lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] Strict chain  ...  192.168.24.161:1080  ...  registry.npmjs.org:443  ...  OKallable status

> pty.js@0.3.1 install /usr/local/node/lib/node_modules/pty.js
> node-gyp rebuild

[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/node/lib/node_modules/pty.js/build'
gyp ERR! System Linux 2.6.39-200.24.1.el6uek.x86_64
gyp ERR! command "/usr/local/node/bin/node" "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/node/lib/node_modules/pty.js
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-15T02_05_42_722Z-debug.log

```
# cat /root/.npm/_logs/2017-09-15T02_05_42_722Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node/bin/node',
1 verbose cli   '/usr/local/node/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'pty.js' ]
2 info using npm@5.4.2
3 info using node@v8.4.0
4 verbose npm-session 0707af25e1362efe
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/pty.js 18ms (from cache)
8 silly pacote tag manifest for pty.js@latest fetched in 50ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule pty.js@0.3.1 checking installable status
14 http fetch GET 200 https://registry.npmjs.org/nan 164ms (from cache)
15 silly pacote version manifest for nan@2.3.5 fetched in 167ms
16 silly resolveWithNewModule nan@2.3.5 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/extend 1250ms (from cache)
18 silly pacote range manifest for extend@~1.2.1 fetched in 1252ms
19 silly resolveWithNewModule extend@1.2.1 checking installable status
20 silly currentTree lib
21 silly idealTree lib
21 silly idealTree ‚îî‚îÄ‚î¨ pty.js@0.3.1
21 silly idealTree   ‚îú‚îÄ‚îÄ extend@1.2.1
21 silly idealTree   ‚îî‚îÄ‚îÄ nan@2.3.5
22 silly install generateActionsToTake
23 silly diffTrees action count 3
24 silly diffTrees add extend@1.2.1
25 silly diffTrees add nan@2.3.5
26 silly diffTrees add pty.js@0.3.1
27 silly decomposeActions action count 24
28 silly decomposeActions fetch extend@1.2.1
29 silly decomposeActions extract extend@1.2.1
30 silly decomposeActions preinstall extend@1.2.1
31 silly decomposeActions build extend@1.2.1
32 silly decomposeActions install extend@1.2.1
33 silly decomposeActions postinstall extend@1.2.1
34 silly decomposeActions finalize extend@1.2.1
35 silly decomposeActions refresh-package-json extend@1.2.1
36 silly decomposeActions fetch nan@2.3.5
37 silly decomposeActions extract nan@2.3.5
38 silly decomposeActions preinstall nan@2.3.5
39 silly decomposeActions build nan@2.3.5
40 silly decomposeActions install nan@2.3.5
41 silly decomposeActions postinstall nan@2.3.5
42 silly decomposeActions finalize nan@2.3.5
43 silly decomposeActions refresh-package-json nan@2.3.5
44 silly decomposeActions fetch pty.js@0.3.1
45 silly decomposeActions extract pty.js@0.3.1
46 silly decomposeActions preinstall pty.js@0.3.1
47 silly decomposeActions build pty.js@0.3.1
48 silly decomposeActions install pty.js@0.3.1
49 silly decomposeActions postinstall pty.js@0.3.1
50 silly decomposeActions finalize pty.js@0.3.1
51 silly decomposeActions refresh-package-json pty.js@0.3.1
52 silly install executeActions
53 silly doSerial global-install 24
54 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
55 verbose lock using /root/.npm/_locks/staging-4be64ed71d05c05a.lock for /usr/local/node/lib/node_modules/.staging
56 silly doParallel extract 24
57 silly extract extend@1.2.1
58 silly pacote trying extend@https://registry.npmjs.org/extend/-/extend-1.2.1.tgz by hash: sha1-oPX9bPyDpf5J72mNYOyKYk3UV2w=
59 silly extract nan@2.3.5
60 silly pacote trying nan@https://registry.npmjs.org/nan/-/nan-2.3.5.tgz by hash: sha1-gioNwmYpDOTNOhIoLKPn42Rmigg=
61 silly extract pty.js@0.3.1
62 silly pacote trying pty.js@https://registry.npmjs.org/pty.js/-/pty.js-0.3.1.tgz by hash: sha1-gfW+0zLW5eeraFaI0boDc0ENUbU=
63 silly pacote extend@https://registry.npmjs.org/extend/-/extend-1.2.1.tgz extracted to /usr/local/node/lib/node_modules/.staging/extend-36d63ef6 by content address 31ms
64 silly pacote pty.js@https://registry.npmjs.org/pty.js/-/pty.js-0.3.1.tgz extracted to /usr/local/node/lib/node_modules/.staging/pty.js-7807ddd2 by content address 36ms
65 silly pacote nan@https://registry.npmjs.org/nan/-/nan-2.3.5.tgz extracted to /usr/local/node/lib/node_modules/.staging/nan-1abb122a by content address 41ms
66 silly doReverseSerial unbuild 24
67 silly doSerial remove 24
68 silly doSerial move 24
69 silly doSerial finalize 24
70 silly finalize /usr/local/node/lib/node_modules/pty.js/node_modules/extend
71 silly finalize /usr/local/node/lib/node_modules/pty.js/node_modules/nan
72 silly finalize /usr/local/node/lib/node_modules/pty.js
73 silly doParallel refresh-package-json 24
74 silly refresh-package-json /usr/local/node/lib/node_modules/pty.js/node_modules/extend
75 silly refresh-package-json /usr/local/node/lib/node_modules/pty.js/node_modules/nan
76 silly refresh-package-json /usr/local/node/lib/node_modules/pty.js
77 silly doParallel preinstall 24
78 silly preinstall extend@1.2.1
79 info lifecycle extend@1.2.1~preinstall: extend@1.2.1
80 silly preinstall nan@2.3.5
81 info lifecycle nan@2.3.5~preinstall: nan@2.3.5
82 silly preinstall pty.js@0.3.1
83 info lifecycle pty.js@0.3.1~preinstall: pty.js@0.3.1
84 silly doSerial build 24
85 silly build extend@1.2.1
86 info linkStuff extend@1.2.1
87 silly linkStuff extend@1.2.1 has /usr/local/node/lib/node_modules/pty.js/node_modules as its parent node_modules
88 silly linkStuff extend@1.2.1 is part of a global install
89 silly linkStuff extend@1.2.1 is installed into a global node_modules
90 verbose linkBins extend@1.2.1
91 verbose linkMans extend@1.2.1
92 silly build nan@2.3.5
93 info linkStuff nan@2.3.5
94 silly linkStuff nan@2.3.5 has /usr/local/node/lib/node_modules/pty.js/node_modules as its parent node_modules
95 silly linkStuff nan@2.3.5 is part of a global install
96 silly linkStuff nan@2.3.5 is installed into a global node_modules
97 verbose linkBins nan@2.3.5
98 verbose linkMans nan@2.3.5
99 silly build pty.js@0.3.1
100 info linkStuff pty.js@0.3.1
101 silly linkStuff pty.js@0.3.1 has /usr/local/node/lib/node_modules as its parent node_modules
102 silly linkStuff pty.js@0.3.1 is part of a global install
103 silly linkStuff pty.js@0.3.1 is installed into a global node_modules
104 silly linkStuff pty.js@0.3.1 is installed into the top-level global node_modules
105 verbose linkBins pty.js@0.3.1
106 verbose linkMans pty.js@0.3.1
107 silly doSerial global-link 24
108 silly doParallel update-linked 24
109 silly doSerial install 24
110 silly install extend@1.2.1
111 info lifecycle extend@1.2.1~install: extend@1.2.1
112 silly install nan@2.3.5
113 info lifecycle nan@2.3.5~install: nan@2.3.5
114 silly install pty.js@0.3.1
115 info lifecycle pty.js@0.3.1~install: pty.js@0.3.1
116 verbose lifecycle pty.js@0.3.1~install: unsafe-perm in lifecycle false
117 verbose lifecycle pty.js@0.3.1~install: PATH: /usr/local/node/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/node/lib/node_modules/pty.js/node_modules/.bin:/usr/local/node/lib/node_modules/.bin:/usr/lib/java/jdk1.7.0_25/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/apache-ant-1.9.9/bin:/root/bin:/usr/local/svn/bin:/usr/local/node/bin
118 verbose lifecycle pty.js@0.3.1~install: CWD: /usr/local/node/lib/node_modules/pty.js
119 silly lifecycle pty.js@0.3.1~install: Args: [ '-c', 'node-gyp rebuild' ]
120 silly lifecycle pty.js@0.3.1~install: Returned: code: 1  signal: null
121 info lifecycle pty.js@0.3.1~install: Failed to exec install script
122 verbose unlock done using /root/.npm/_locks/staging-4be64ed71d05c05a.lock for /usr/local/node/lib/node_modules/.staging
123 verbose stack Error: pty.js@0.3.1 install: `node-gyp rebuild`
123 verbose stack Exit status 1
123 verbose stack     at EventEmitter.<anonymous> (/usr/local/node/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
123 verbose stack     at emitTwo (events.js:125:13)
123 verbose stack     at EventEmitter.emit (events.js:213:7)
123 verbose stack     at ChildProcess.<anonymous> (/usr/local/node/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
123 verbose stack     at emitTwo (events.js:125:13)
123 verbose stack     at ChildProcess.emit (events.js:213:7)
123 verbose stack     at maybeClose (internal/child_process.js:927:16)
123 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
124 verbose pkgid pty.js@0.3.1
125 verbose cwd /root
126 verbose Linux 2.6.39-200.24.1.el6uek.x86_64
127 verbose argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install" "-g" "pty.js"
128 verbose node v8.4.0
129 verbose npm  v5.4.2
130 error code ELIFECYCLE
131 error errno 1
132 error pty.js@0.3.1 install: `node-gyp rebuild`
132 error Exit status 1
133 error Failed at the pty.js@0.3.1 install script.
133 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by pablodgonzalez** [comment]
@chjj @hktalent same here. Is there some solution?

**Comment by Tyriar** [comment]
@pablodgonzalez you can try https://github.com/Tyriar/node-pty which is a maintained fork of this project. I haven't tested it under npm 8 yet but I expect it to work.

**Comment by troymaclure** [comment]
Same here : on osx, high sierra, trying to re-install terminal-recorder after it didn't work properly anymore.

I'm pretty new to Node.Js. I'm not quite sure what you mean by "you can try... node-pty". I tried to install it with npm, but I have the exact same issues as above, except it's now node-pty instead of pty.js.

Is there a way to install it manually ? 

It feels like the whole thing is broken.

**Comment by Tyriar** [comment]
@stephanepiriou the error kind of looks like you messed up your node install as the current user doesn't have access to create folders within it: `EACCES: permission denied`. If so maybe fiddling with `npm config set prefix` to use a folder inside `$HOME` might help, you should be able to find guides on how to do this on the internet.

**Comment by troymaclure** [comment]
I found another thread about a bug somewhat similar to this, with a permission issue. It seems I saw something like this. I have to find the page again.

In fact, i had an issue with Macport or Brew while installing node which didn't had access to some folder in /usr/local or /usr/bin in order to finish the installation... I changed permission in a not so subtil way with a chmod well placed... 

I will find my way.
Thanks.

**Comment by hktalent** [comment]
same,kali linux,

```
#node -v
v10.12.0
npm@6.5.0
#npm i -g node-pty

> node-pty@0.8.0 install /root/mytools/node-v10.12.0-linux-x64/lib/node_modules/node-pty
> node scripts/install.js

module.js:550
    throw err;
    ^

Error: Cannot find module '/root/mytools/node-v10.12.0-linux-x64/lib/node_modules/node-pty/scripts/install.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.8.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty@0.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-04T05_39_09_571Z-debug.log
```
