### ISSUE TITLE
can not install on MACOSX with node- 0.11.11

### ISSUE THREAD

**Issue by anandkumarpatel** [chjj/pty.js#62]
I am seeing the following issue when trying to install pty.js-11 on mac with node 0.11.11
where is wait.h supposed to come from?

```
Darwin 13.0.2 Darwin Kernel Version 13.0.2: Sun Sep 29 19:38:57 PDT 2013; root:xnu-2422.75.4~1/RELEASE_X86_64 x86_64
```

```
dockworker$ npm install pty.js-11
npm WARN package.json dockworker@0.0.3 No repository field.
npm http GET https://registry.npmjs.org/pty.js-11
npm http 304 https://registry.npmjs.org/pty.js-11
npm http GET https://registry.npmjs.org/nan/0.7.0
npm http GET https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/nan/0.7.0
npm http 304 https://registry.npmjs.org/extend

> pty.js-11@0.2.5 install /Users/anand/run/dockworker/node_modules/pty.js-11
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc:220:10: fatal error: 'wait.h' file not found
#include <wait.h>
         ^
1 error generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:879:12)
gyp ERR! System Darwin 13.0.2
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/anand/run/dockworker/node_modules/pty.js-11
gyp ERR! node -v v0.11.11
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! pty.js-11@0.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js-11@0.2.5 install script.
npm ERR! This is most likely a problem with the pty.js-11 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js-11
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.0.2
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pty.js-11"
npm ERR! cwd /Users/anand/run/dockworker
npm ERR! node -v v0.11.11
npm ERR! npm -v 1.3.25
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/anand/run/dockworker/npm-debug.log
npm ERR! not ok code 0
dockworker$ cat /Users/anand/run/dockworker/npm-debug.log
```

**Comment by tijs14tijs** [comment]
I get the same issue, but for me the file /usr/include/util.h cannot be found.
