### ISSUE TITLE
File is missing '../build/Release/pty.node' 

### ISSUE THREAD

**Issue by omarragi** [chjj/pty.js#89]
after installing tty.js
pty.js/lib/pty.js is pointing to a file that doesn't exist

/**
- pty.js
- Copyright (c) 2012, Christopher Jeffrey (MIT License)
- Binding to the pseudo terminals.
  */

var net = require('net');
var tty = require('tty');
var extend = require('extend');
var pty = require('../build/Release/pty.node');

module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Release/pty.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/oragi/tt/node_modules/tty.js/node_modules/pty.js/lib/pty.js:10:11)
    at Module._compile (module.js:456:26)

**Comment by lordnynex** [comment]
Hello,

Thanks for the cool module. It will replace many janky bash scripts. 

I ran into this issue and spent the last hour trying to figure out why node-gyp was being so stubborn. Turns out, I built node (0.12.2) awhile back with debug symbols. In turn, node-gyp compiles this module only in Debug. 

The solution is to cd into the module dir ```make clean && node-gyp configure --release && node-gyp build```

I didn't realize node-gyp did this.
